plugins {
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
    id 'gg.essential.multi-version'
    id 'gg.essential.defaults.repo'
    id 'gg.essential.defaults.java'
    id 'gg.essential.defaults.loom'
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    maven {
        name "KosmX's maven"
        url 'https://maven.kosmx.dev/'
    }
    maven { url = "https://maven.florens.be/releases" }
    repositories {
        maven { url 'https://maven.wispforest.io' }
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
}

dependencies {
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${platform.mcVersionStr}:$project.parchment_version@zip")
    }

    include modImplementation("dev.kosmx.player-anim:player-animation-lib-${platform.loaderStr}:${project.player_animator_version}")
    include modImplementation("be.florens:expandability-${platform.loaderStr}:${project.expandability_version}")

    modImplementation "io.wispforest:owo-lib:${project.owo_version}"
    annotationProcessor "io.wispforest:owo-lib:${project.owo_version}"
    include "io.wispforest:owo-sentinel:${project.owo_version}"
}