# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.21.1-1.6
maven_group=me.mfletcher.homing
archives_name=homing
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.16.14
fabric_api_version=0.116.3+1.21.1
neoforge_version=21.1.182
parchment_version=2024.11.17
player_animator_version=2.0.1+1.21.1
expandability_version=12.0.0
fzzy_version=0.7.0+1.21