modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mfletcher2/homingattack-boost-mod/issues"
license = "GPL-3.0"

[[mods]]
modId = "homing"
version = "${version}"
displayName = "Homing Attack"
authors = "mfletcher"
description = '''
Sonic's Homing Attack and Boost in Minecraft
'''
logoFile = "assets/homing/icon.png"
displayURL = "https://github.com/mfletcher2/homingattack-boost-mod"

[[dependencies.homing]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.homing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.homing]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.homing]]
modId = "fzzy_config"
mandatory = true
versionRange = "[0.7.0,)"